<?php
error_reporting(E_ALL);

$page_title = "EXPA &middot; XPDF";
require_once "lib/init.php";
require_once "lib/library.inc.php";
require_once "head.php";

$gip_companies = ["Muthoot", "Punj Lloyd", "Crest Animation Studios", "Financial Technologies Group", "Muthoot Finance Ltd", "UltraTech Cement", "Eveready Industries India", "HDFC Bank", "Tata Interactive Systems", "Bharat Aluminium Company", "Organic India", "iball", "Deccan Charters", "Zoho Corp.", "Zomato", "Voonik", "Hindustan Petroleum", "Bharat Petroleum", "Reliance Capital", "Welspun Syntex Ltd", "NDTV", "See also", "Café Coffee Day", "Ajanta Group", "Vijaya Bank", "Idea Cellular", "Engineers India Limited", "RPG Group", "Tavant Technologies", "Fortis Healthcare", "Hindustan Motors", "Crompton Greaves", "Vicco Group", "Dena Bank", "Jabong.com", "Rashtriya Chemicals & Fertilizers", "Rashtriya Ispat Nigam", "Paragon footwear", "Ordnance Factories Board", "Jaiprakash Associates", "Steel Authority of India Limited", "Vizag Steel", "PromptCloud", "Camlin Ltd.", "Cipla", "Rediff.com", "Reliance Infrastructure", "National Mineral Development Corp.", "Reliance ADA Group", "Flipkart"];
$gcdp_ngos = ["The Akanksha Foundation", "Childline India Foundation", "Paragon Charitable Trust", "K.C. Mahindra Education Trust", "The Research Society for the Care of Children", "Save The Children India", "Shrimad Rajchandra Love and Care", "Concern India Foundation", "Aseema Charitable Trust", "CRY - Child Rights and You", "Mumbai Mobile Creches", "Cancer Patients Aid Association", "Helen Keller Institute for Deaf & Deafblind", "ISHA Education", "Bhagwan Mahaveer Viklang Sahayata Samiti", "Iskcon Food Relief Foundation", "Project Crayons", "Rotary Club Bombay", "Deeds Public Charitable Trust", "Swayamsiddh Matimand Mulansathi M.S.", "National Liver Foundation", "Alert India", "Apnalaya", "Vasantha Memorial Trust", "Catalysts for Social Action", "ChildLink India Foundation", "Dignity Foundation", "Teach to Lead", "Vidya Integrated Development For Youth and Adults", "Sanskriti Samvardhan Mandal", "Salaam Baalak Trust", "The Indian Council for Mental Health", "Ummeed Child Development Center", "HelpAge India", "Kherwadi Social Welfare Association", "Atma Education", "Make a Wish Foundation of India", "AMAR SEVA SANGAM", "The Society For Door Step school", "Seva Sadan Society", "Maharashtra Dyslexia Association", "The Foundation", "Girivanvasi Educational Trust", "Ballygunge Society for Children In Pain", "Americares India Foundation", "The Vatsalya Foundation", "Nana Nani Foundation", "Light of Life Trust", "The Education Audiology & Research Society", "Apne Aap Women's Collective"];
$peeps = [ 1 => [ "Aswini Madan", "Abigail Nigam", "Gayatri Nath", "Rohit Uddin", "Natasha Kapoor", "Vinay Chandrasekar", "Ira Bhat", "Sanjana Raji", "Soham Veena", "Naveen Swami", "Shyam Jana", "Priya Kumar", "Aastha Nirmal", "Abhishek Sahni", "Vikas Srivas", "Divya Shan", "Nishi Mehta", "Tanu Malik", "Anisha Mittal", "Abhi Sandeep", "Jay Samuel", "Riya Chander", "Manish Rastogi", "Niharika Anand", "Neha Chandra", "Akansha Nita", "Akash Gandhi", "Nitin Srivastav", "Krishna Ganesh", "Ishita Pal", "Rohan Manju", "Parth Soni", "Arjun Mehra", "Isha Malhotra", "Shivam Bhatt"], 2 => [ "Krithika Narayan", "Seema Rana", "Siya Charan", "Vivek Nagpal", "Kunal Srivastava", "Rahul Manohar", "Krish Jin", "Rishita Subramanian", "Tanvi Jai", "Ananya Sai", "Aaditya Joshi", "Ankur Muthu", "Raju Mati", "Radhika Vijaya", "Shreya Chande", "Raj Vish", "Abhinav Punj", "Ashish Neela", "Rishabh Veer", "Karan Lata", "Mayank Dhawan", "Aditya Lalit", "Sneha Nara", "Sanjay Neelam", "Manoj Puri", "Mary Pawan", "Pranav Mahajan", "Leah Prasad", "Diya Chaudhary", "Tanya Lal", "Simran Subram", "Neeraj Krishnamurthy", "Sakshi Arun" ], 3 => [ "Vishal Sudha", "Yash Saini", "Priyanka Sharma", "Nishant Rajagopal", "Sadaf Kishore", "Anjali Raje", "Varsha Goel", "Ajith Dutta", "Ramya Verma", "Prateek Narang", "Aishwarya Rai", "Shivangi Patel", "Vani Aggarwal", "Aryan Ranga", "Deepak Darsha", "Mahesh Sehgal", "Nikita Suri", "Suhani Srini", "Raghav Naran", "Rakesh Chauhan", "Ayushi Sethi", "Shivani Engineer", "Anusha Raman", "Amit Rajan", "Ankit Neel", "Pavithra Sara", "Kumar Persaud", "Sam Saxena", "Kalyani Sen", "Anushri Subramani", "Vaibhav Tyagi", "Nishita Roy" ]];
?>
<div class="container" style="width: 60%; font-size: 24px;">
<form class="bigform" action="submit.php" method="POST">
	<input type="hidden" name="act" value="addform">
	<b>Type</b>: <input type="radio" name="type" id="tn" value="tn" onChange="$('.ogx').hide();$('.icx').show()"> <label for="tn">Opportunity</label>
	<input type="radio" name="type" id="ep" value="ep" onChange="$('.icx').hide();$('.ogx').show()"> <label for="ep">Person</label><br>
	<div class="icx ogx"><b>Product</b>: <input type="radio" name="prog" id="gcdp" value="gcdp" onChange="$('.gip').hide();$('.gcdp').show()"> <label for="gcdp">Global Volunteer</label>
	<input type="radio" name="prog" id="gip" value="gip" onChange="$('.gcdp').hide();$('.gip').show()"> <label for="gip">Global Talent</label></div>
	<div class='icx'><b>Field</b>: <select name="field"><?php foreach ($fields as $key => $field) echo "<option value='$key'>$field</option>"; ?></select></div>
	<div class='icx'><div class='gip'><b>Organization</b>: <select name="oname"><?php foreach ($gip_companies as $gip_company) echo "<option value='$gip_company'>$gip_company</option>"; ?></select>
	<div class='icx'><b>Salary</b>: Rs. <input type='number' name='salary' step='1000' value='20000'></div></div>
	<div class='gcdp'><b>NGO</b>: <select name="nname"><?php foreach ($gcdp_ngos as $gcdp_ngo) echo "<option value='$gcdp_ngo'>$gcdp_ngo</option>"; ?></select></div></div>
	<div class='ogx'><b>Name(s)</b>: <select class="gcdp" multiple name="ename_gcdp[]" style='height: 300px;'><?php foreach ($peeps as $key => $peep) { sort($peep); echo "<optgroup label='".$fields[$key+3]."'>"; foreach ($peep as $person) echo "<option value='".($key+3).".$person'>$person</option>"; echo "</optgroup>"; } ?></select><select class="gip" multiple name="ename_gip[]" style='height: 300px;'><?php foreach ($peeps as $key => $peep) { sort($peep); echo "<optgroup label='{$fields[$key]}'>"; foreach ($peep as $person) echo "<option value='$key.$person'>$person</option>"; echo "</optgroup>"; } ?></select></div>
	<div class='icx'><b>No. of Interns</b>: <input type='number' name='noforms' min='1' max='20' value='1'></div>
	<?php if (!NO_COUNTRY_PREFS): ?><div class='gip gcdp'><b>Entity Preferences</b>: <?php foreach ($teams as $tid => $team) echo "<nobr><input type='checkbox' name='countrypref[]' value='$tid' id='team$tid'> <label for='team$tid'>{$team['tcodename']}</label></nobr> &nbsp;"; ?> <input type="button" onClick='for (var i = 1; i <= 15; i++) { $("#team"+i).attr("checked", "checked"); }' value="All"></div><?php endif; ?>
	<!-- <div class='gip gcdp'><b><span class='ogx'>Availability</span><span class='icx'>Min. Start Date</span></b>: <input type='date' name='startdate' min='2016-01-01' max='2016-12-31'></div> -->
	<b>Form Opened By</b>: <select name="raisedby"><?php foreach ($teams as $key => $team) echo "<option value='$key'>{$team['tcodename']}</option>"; ?></select><br>
	<b>Faci Number</b>: <input type='number' name='facinumber' min='1' max='200'><br>
	<div class='gcdp gip'><div class='icx'><input type='submit' value='Add Form'></div><div class='ogx'><input type='submit' value='Register User'></div></div>
</form>
